# Start from the Jenkins LTS image
FROM jenkins/jenkins:lts

# Switch to root to install packages
USER root

# Install Docker CLI plugin inside the Jenkins container
RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

# Allow Jenkins to access Docker socket
RUN usermod -aG docker jenkins

# Go back to Jenkins user
USER jenkins